sudo: required

services:
  - docker

before_install:
  - docker build -t dogliy/multi-client  -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dogliy/multi-client npm run test

after_sucess:
  - docker build -t dogliy/multi-client ./client
  - docker build -t dogliy/multi-nginx ./nginx
  - docker build -t dogliy/multi-worker ./worker
  - docker build -t dogliy/multi-backend ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dogliy/multi-client
  - docker push dogliy/multi-nginx
  - docker push dogliy/multi-worker
  - docker push dogliy/multi-backend

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-745665539209"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  