version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - /app/node_modules
      - ./server/:/app
    depends_on:
      - redis
      - postgres
    environment:
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_DATABASE=postgres
      - PG_PORT=5432
      - PG_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - backend
      - client
    ports:
      - 80:80
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client/:/app
    depends_on:
      - backend
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    
  redis:
    image: redis:latest
