version: "3"

services:
  vote:
    image: bretfisher/examplevotingapp_vote
    ports:
      - 5000:80
    networks:
      - frontend
    deploy:
      replicas: 2
  redis:
    image: redis:3.2
    networks:
      - frontend
    deploy:
      replicas: 1
  worker:
    image: bretfisher/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
  db:
    image: postgres:9.4
    networks:
      - backend
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    deploy:
      replicas: 1
  result:
    image: bretfisher/examplevotingapp_result
    networks:
      - backend
    ports:
      - 5001:80
    volumes:
      - db-data:/var/lib/postgresql/data

  visualizer:
    image: dockersamples/visualizer
    ports:
      - 8080:8080
    networks:
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role==manager]

networks:
  backend:
  frontend:
volumes:
  db-data: