version: '3'

services:
    drupal:
      image: drupal-test-1
      build: .
      ports:
        - '80:80'
      volumes:
        - drupal-modules:/var/www/html/modules
        - drupal-profiles:/var/www/html/profiles
        - drupal-sites:/var/www/html/sites
        - drupal-themes:/var/www/html/themes
    postgres:
      image: postgres:12.1
      volumes:
        - 'drupal-data:/var/lib/postgresql/data'
      environment:
        - 'POSTGRES_PASSWORD=60056005'
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  postgres-db:
  drupal-data:
