apiVersion: v1
kind: Service
metadata:
  name: backend-node-port-service
spec:
  type: NodePort
  selector:
    component: backend
  ports:
    - port: 3050
      targetPort: 8081
      nodePort: 30001