module.exports={
    redisHost:process.env.REDIS_HOST,
    redisPort:process.env.REDIS_PORT,
    pgUser:process.env.PG_USER,
    pgPort:process.env.PG_PORT,
    pgHost:process.env.PG_HOST,
    pgDatabase:process.env.PG_DATABASE,
    pgPassword:process.env.PG_PASSWORD
}