version: '3'


services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client/:/app
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - /app/node_modules
      - ./server/:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=password
    depends_on:
      - postgres
  redis:
    image: redis:latest
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379