sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t dogliy/react-learn-1 -f Dockerfile.dev .

script:
  - docker run -e CI=true dogliy/react-learn-1 npm run test