version: "3.1"

services:
  sql:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - my-sql-network
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql_pass
      - POSTGRES_USER_FILE=/run/secrets/psql_user
    secrets:
      - psql_pass
      - psql_user
networks:
  my-sql-network:

secrets:
  psql_pass:
    external: true
  psql_user:
    external: true