version: '3'

services:
  react-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:3000'
    volumes: 
      - ./:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm","run","test"]
    volumes: 
      - ./:/app
    
