sudo: required

services:
  - docker

before_install:
  - docker build -t dogliy/react-learn -f Dockerfile.dev .

script:
  - docker run -e CI=true dogliy/react-learn npm run test

depoly:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-745665539209"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY   