version: '3'

services:
  client:
    image: dogliy/multi-client
    mem_limit: 128m
    hostname: client
  server:
    image: "dogliy/multi-server"
    mem_limit: 128m
    hostname: api
    restart: always
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: dogliy/multi-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: dogliy/multi-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - 80:80
