sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dogliy/react-learn-1 -f Dockerfile.dev .
script:
  - docker run -e CI=ture dogliy/react-learn-1 npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-745665539209"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
  
